"""Initialize CarabinerOS database and API routes at A0 startup.

1. Creates tables (if missing) via metadata.create_all
2. Initializes the async connection pool
3. Writes thin A0 ApiHandler stubs to /a0/api/ so A0's dispatch
   serves /api/orders, /api/prep, etc. from the CarabinerOS DB
"""

import asyncio
import os
from pathlib import Path

from helpers.extension import Extension
from helpers.print_style import PrintStyle


# A0 ApiHandler stub template — written to /a0/api/<resource>.py
_HANDLER_STUB = '''\
"""Auto-generated by CarabinerOS startup — do not edit."""
from carabiner.api._a0_handlers import make_handler
Handler = make_handler("{resource}")
'''

_CUSTOM_STUB = '''\
"""Auto-generated by CarabinerOS startup — do not edit."""
from carabiner.api._a0_handlers import {factory}
Handler = {factory}()
'''

# Resources to expose via A0's /api/<name> dispatch
_RESOURCES = [
    "orders",
    "inventory",
    "prep",
    "food-cost",
    "menu",
    "recipes",
    "invoices",
    "campaigns",
]

# Sub-routes with custom handlers: (path, factory_function_name)
_CUSTOM_ROUTES = [
    ("food-cost/summary", "make_food_cost_summary_handler"),
    ("food-cost/daily", "make_food_cost_daily_handler"),
    ("food-cost/budget", "make_food_cost_budget_handler"),
    ("vendors", "make_vendors_handler"),
    ("inventory/valuation", "make_inventory_valuation_handler"),
    ("inventory/counts", "make_inventory_counts_handler"),
    ("inventory/par-levels", "make_inventory_par_levels_handler"),
    ("inventory/waste", "make_inventory_waste_handler"),
    ("prep/today", "make_prep_today_handler"),
    ("chats", "make_chats_handler"),
    ("message", "make_message_handler"),
    ("message_async", "make_message_async_handler"),
    ("csrf_token", "make_csrf_token_handler"),
]


class CarabinerInit(Extension):
    def execute(self, **kwargs):
        try:
            db_url = os.environ.get(
                "DATABASE_URL",
                "postgresql+asyncpg://carabiner:carabiner@localhost:5432/carabiner",
            )
            from carabiner.db.base import Base
            import carabiner.db.models  # noqa: F401
            import carabiner.db.workspace_models  # noqa: F401

            loop = asyncio.new_event_loop()

            async def _setup():
                from sqlalchemy.ext.asyncio import create_async_engine

                engine = create_async_engine(db_url)
                async with engine.begin() as conn:
                    await conn.run_sync(Base.metadata.create_all)
                await engine.dispose()
                # Don't call init_db here — the startup loop differs from
                # A0's uvicorn loop. get_session() creates fresh engines
                # per-request via its fallback path.

            loop.run_until_complete(_setup())
            loop.close()

            PrintStyle(
                background_color="#059669", font_color="white", padding=True
            ).print("CarabinerOS database connected")

            # Write API handler stubs so A0 dispatch serves workspace data
            self._register_api_stubs()

        except Exception as e:
            PrintStyle(
                background_color="red", font_color="white", padding=True
            ).print(f"CarabinerOS DB init failed (non-fatal): {e}")

    def _register_api_stubs(self):
        api_dir = Path("/a0/api")
        count = 0
        for resource in _RESOURCES:
            stub_path = api_dir / f"{resource}.py"
            if not stub_path.exists():
                stub_path.write_text(_HANDLER_STUB.format(resource=resource))
                count += 1
        for route_path, factory in _CUSTOM_ROUTES:
            stub_path = api_dir / f"{route_path}.py"
            stub_path.parent.mkdir(parents=True, exist_ok=True)
            if not stub_path.exists():
                stub_path.write_text(_CUSTOM_STUB.format(factory=factory))
                count += 1
        if count:
            PrintStyle(
                background_color="#059669", font_color="white", padding=True
            ).print(f"CarabinerOS API: {count} endpoints registered")
